{
  "pipe_parallel_size": 4,
  "model_parallel_size": 8,
  "num_layers": 16,
  "hidden_size": 2048,
  "num_attention_heads": 8,
  "seq_length": 2048,
  "max_position_embeddings": 2048,
  "pos_emb": "rotary",
  "rotary_pct": 0.25,
  # "mlp_type": "llama",
  # "activation": "silu",
  "no_weight_tying": true,
  "gpt_j_residual": true,
  "output_layer_parallelism": "column",
  # "attention_config": [[["flash"], 24]],
   "scaled_upper_triang_masked_softmax_fusion": false,
   "bias_gelu_fusion": false,
   "rope_fusion": false,
   "layernorm_fusion": false,
  "optimizer": {
    "type": "Adam",
    "params": {
      "lr": 5.0e-4,
      "betas": [0.9, 0.95],
      "eps": 1.0e-8,
    }
  },
  "min_lr": 5.0e-5,
  "lr_decay_style": "cosine",
  "warmup": 0.01,
   "zero_optimization": {
    "stage": 1,
    "allgather_partitions": true,
    "allgather_bucket_size": 200000000,
    "overlap_comm": true,
    "reduce_scatter": true,
    "reduce_bucket_size": 200000000,
    "contiguous_gradients": true,
    "cpu_offload": false
  },
   "train_micro_batch_size_per_gpu": 4,
   "gradient_accumulation_steps": 1,
   "data_impl": "mmap",
   "checkpoint_activations": true,
   "checkpoint_num_layers": 1,
   "partition_activations": true,
   "synchronize_each_layer": true,
   "gradient_clipping": 1.0,
   "weight_decay": 0.1,
   "hidden_dropout": 0.0,
   "attention_dropout": 0.0,
  "precision": "bfloat16",
  "fp32_allreduce": true,
  "bf16": {
    "enabled": true
  },
  "data_types": {
    "grad_accum_dtype": "fp32"
  },
   "train_iters": 143000,
   "lr_decay_iters": 143000,
   "distributed_backend": "nccl",
   "checkpoint_factor": 1000,
   "eval_interval": 10,
   "eval_iters": 10,
   "log_interval": 10,
   "steps_per_print": 10,
   "keep_last_n_checkpoints": 4,
   "wall_clock_breakdown": true,
   "launcher": "slurm",
   "deepspeed_slurm": true,
   "num_workers": 8,
    "train_data_paths": [
    "/lustre/orion/bif151/proj-shared/data/slim_pajama/tokenized_train_0-200B/CommonCrawl/CommonCrawl",
    "/lustre/orion/bif151/proj-shared/data/slim_pajama/tokenized_train_0-200B/C4/C4",
    "/lustre/orion/bif151/proj-shared/data/slim_pajama/tokenized_train_0-200B/Github/Github",
    "/lustre/orion/bif151/proj-shared/data/slim_pajama/tokenized_train_0-200B/Book/Book",
    "/lustre/orion/bif151/proj-shared/data/slim_pajama/tokenized_train_0-200B/ArXiv/ArXiv",
    "/lustre/orion/bif151/proj-shared/data/slim_pajama/tokenized_train_0-200B/Wikipedia/Wikipedia",
    "/lustre/orion/bif151/proj-shared/data/slim_pajama/tokenized_train_0-200B/StackExchange/StackExchange",],   "test_data_paths": ["/lustre/orion/bif151/proj-shared/data/slim_pajama/test/all/sp_test",],
   "valid_data_paths": ["/lustre/orion/bif151/proj-shared/data/slim_pajama/test/all/sp_test",],
  "train_data_weights": [
    2.3135984956768517,
    1.0029210688085275,
    10.09463376920134,
    2.5361521690611304,
    3.3329762632854697,
    2.121055878176133,
    15.33199568912388,],
  "train_proportion": [
    0.18,
    0.18,
    0.18,
    0.1458, # don't cross this value !
    0.13,
    0.11585539362,
    0.017362557217,],
    
  "test_data_paths": ["/lustre/orion/bif151/proj-shared/data/slim_pajama/test/all/sp_test",],
  # "valid_data_paths": [    "/lustre/orion/bif151/proj-shared/data/slim_pajama/tokenized_train_0-200B/CommonCrawl/CommonCrawl",
  #   "/lustre/orion/bif151/proj-shared/data/slim_pajama/tokenized_train_200B-300B/CommonCrawl/CommonCrawl",
  #   "/lustre/orion/bif151/proj-shared/data/slim_pajama/tokenized_train_0-200B/C4/C4",
  #   "/lustre/orion/bif151/proj-shared/data/slim_pajama/tokenized_train_200B-300B/C4/C4",
  #   "/lustre/orion/bif151/proj-shared/data/slim_pajama/tokenized_train_0-200B/Github/Github",
  #   "/lustre/orion/bif151/proj-shared/data/slim_pajama/tokenized_train_200B-300B/Github/Github",
  #   "/lustre/orion/bif151/proj-shared/data/slim_pajama/tokenized_train_0-200B/Book/Book",
  #   "/lustre/orion/bif151/proj-shared/data/slim_pajama/tokenized_train_200B-300B/Book/Book",
  #   "/lustre/orion/bif151/proj-shared/data/slim_pajama/tokenized_train_0-200B/ArXiv/ArXiv",
  #   "/lustre/orion/bif151/proj-shared/data/slim_pajama/tokenized_train_200B-300B/ArXiv/ArXiv",
  #   "/lustre/orion/bif151/proj-shared/data/slim_pajama/tokenized_train_0-200B/Wikipedia/Wikipedia",
  #   "/lustre/orion/bif151/proj-shared/data/slim_pajama/tokenized_train_200B-300B/Wikipedia/Wikipedia",
  #   "/lustre/orion/bif151/proj-shared/data/slim_pajama/tokenized_train_0-200B/StackExchange/StackExchange",
  #   "/lustre/orion/bif151/proj-shared/data/slim_pajama/tokenized_train_200B-300B/StackExchange/StackExchange",],
  "valid_data_paths":["/lustre/orion/bif151/proj-shared/data/slim_pajama/test/all/sp_test",],
  
  "weight_by_num_documents": true,
   "split" : "80,10,10",
   "tokenizer_type": "HFTokenizer",
  #  "vocab_file": "/lustre/orion/bif151/proj-shared/Meta-Llama-3-8B/tokenizer.json",
   "vocab-file": "data/20B_tokenizer.json",
  #  "use_replay": true,
  #  "buffer_size": 3200000000,
  #  "file_size": 3200000,
  #  "replay_buffer_proportion" : 0.5,
  #  "fill_buffer_size": 2000,
   "split" : "80,10,10",
   "tokenizer_type": "HFTokenizer",
  #  "vocab_file": "/lustre/orion/bif151/proj-shared/Meta-Llama-3-8B/tokenizer.json",
   "vocab-file": "data/20B_tokenizer.json",

  #  "buffer_dir": "data/buffer_save/pythia_410M_with_buffer/",
  "deepspeed_mpi": true,
  "save": "checkpoints/pretraining-1B-no-flsh",
  "log_dir": "logs",
  # "load": "checkpoints/pretraining-1B-no-flsh",
  # "tensorboard_dir": "tensorboard_important/pythia_410M_no_buffer_final",
  "wandb_project":"pretraining-1B-no-flsh",
  "wandb_team":"istabrak"
}


