{
  "pipe_parallel_size": 1,
  "model_parallel_size": 1,
  "num_layers": 24,
  "hidden_size": 1024,
  "num_attention_heads": 16,
  "seq_length": 2048,
  "max_position_embeddings": 2048,
  "pos_emb": "rotary",
  "rotary_pct": 0.25,
  # "mlp_type": "llama",
  "activation": "silu",
  "no_weight_tying": true,
  "gpt_j_residual": true,
  "output_layer_parallelism": "column",
  "attention_config": [[["flash"], 16]],
   "scaled_upper_triang_masked_softmax_fusion": false,
   "bias_gelu_fusion": false,
   "rope_fusion": false,
   "layernorm_fusion": false,
  "optimizer": {
    "type": "Adam",
    "params": {
      "lr": 3.0e-4,
      "betas": [0.9, 0.95],
      "eps": 1.0e-8,
    }
  },
  "min_lr": 3.0e-5,
  "lr_decay_style": "cosine",
  "warmup": 0.01,
   "zero_optimization": {
    "stage": 1,
    "allgather_partitions": true,
    "allgather_bucket_size": 500000000,
    "overlap_comm": true,
    "reduce_scatter": true,
    "reduce_bucket_size": 500000000,
    "contiguous_gradients": true,
    "cpu_offload": false
  },
   "train_micro_batch_size_per_gpu": 1,
   "gradient_accumulation_steps": 1,
   "data_impl": "mmap",
   "checkpoint_activations": true,
   "checkpoint_num_layers": 1,
   "partition_activations": true,
   "synchronize_each_layer": true,
   "gradient_clipping": 1.0,
   "weight_decay": 0.1,
   "hidden_dropout": 0.0,
   "attention_dropout": 0.0,
   "fp16": {
     "enabled": true,
     "loss_scale": 0,
     "loss_scale_window": 1000,
     "hysteresis": 2,
     "min_loss_scale": 1
   },
   "train_iters": 132366,
   "lr_decay_iters": 132366,
   "distributed_backend": "nccl",
   "lr_decay_style": "cosine",
   "warmup": 0.01,
   "checkpoint_factor": 1000,
   "eval_interval": 10,
   "eval_iters": 10,
   "log_interval": 10,
   "steps_per_print": 10,
   "keep_last_n_checkpoints": 4,
   "wall_clock_breakdown": true,
   "launcher": "slurm",
   "deepspeed_slurm": true,
   "num_workers": 8,
   "train_data_paths": [
    "/lustre/orion/bif151/proj-shared/data/slim_pajama/tokenized_train_0-200B/CommonCrawl/CommonCrawl",
    "/lustre/orion/bif151/proj-shared/data/slim_pajama/tokenized_train_200B-300B/CommonCrawl/CommonCrawl",
    "/lustre/orion/bif151/proj-shared/data/slim_pajama/tokenized_train_0-200B/C4/C4",
    "/lustre/orion/bif151/proj-shared/data/slim_pajama/tokenized_train_200B-300B/C4/C4",
    "/lustre/orion/bif151/proj-shared/data/slim_pajama/tokenized_train_0-200B/Github/Github",
    "/lustre/orion/bif151/proj-shared/data/slim_pajama/tokenized_train_200B-300B/Github/Github",
    "/lustre/orion/bif151/proj-shared/data/slim_pajama/tokenized_train_0-200B/Book/Book",
    "/lustre/orion/bif151/proj-shared/data/slim_pajama/tokenized_train_200B-300B/Book/Book",
    "/lustre/orion/bif151/proj-shared/data/slim_pajama/tokenized_train_0-200B/ArXiv/ArXiv",
    "/lustre/orion/bif151/proj-shared/data/slim_pajama/tokenized_train_200B-300B/ArXiv/ArXiv",
    "/lustre/orion/bif151/proj-shared/data/slim_pajama/tokenized_train_0-200B/Wikipedia/Wikipedia",
    "/lustre/orion/bif151/proj-shared/data/slim_pajama/tokenized_train_200B-300B/Wikipedia/Wikipedia",
    "/lustre/orion/bif151/proj-shared/data/slim_pajama/tokenized_train_0-200B/StackExchange/StackExchange",
    "/lustre/orion/bif151/proj-shared/data/slim_pajama/tokenized_train_200B-300B/StackExchange/StackExchange",],   "test_data_paths": ["/lustre/orion/bif151/proj-shared/data/slim_pajama/test/all/sp_test",],
   "valid_data_paths": ["/lustre/orion/bif151/proj-shared/data/slim_pajama/test/all/sp_test",],
  "train_data_weights": [
    2.3135984956768517,
    1.1567992478384258,
    2.6029210688085275,
    1.3014605344042638,
    17.09463376920134,
    8.54731688460067,
    2.5361521690611304,
    1.2680760845305652,
    3.3329762632854697,
    1.6664881316427348,
    2.121055878176133,
    1.0605279390880665,
    33.33199568912388,
    16.66599784456194,],
  "train_proportion": [
    0.01476061547,
    0.02802087551,
    0.01401043775,
    0.17792332981,
    0.08896166491,
    0.02664862083,
    0.01332431042,
    0.03482760704,
    0.01741380352,
    0.02247385817,
    0.01123692908,
    0.34725114434,
    0.17362557217,],

   "split" : "80,10,10",
   "tokenizer_type": "HFTokenizer",
  #  "vocab_file": "/lustre/orion/bif151/proj-shared/Meta-Llama-3-8B/tokenizer.json",
   "vocab-file": "data/20B_tokenizer.json",
   "use_replay": true,
   "buffer_size": 3200000000,
   "file_size": 3200000,
   "replay_buffer_proportion" : 0.5,
   "fill_buffer_size": 2000,
   "split" : "80,10,10",
   "tokenizer_type": "HFTokenizer",
  #  "vocab_file": "/lustre/orion/bif151/proj-shared/Meta-Llama-3-8B/tokenizer.json",
   "vocab-file": "data/20B_tokenizer.json",

   "buffer_dir": "data/buffer_save/",
  #  "deepspeed_mpi": true,
  "save": "checkpoints/pythia_410M_with_buffer",
   "log_dir": "logs",
  #  "load": "checkpoints/pythia_410M_15k",
  "tensorboard_dir": "test_tensorboard",
}