# Suggested data paths when using GPT-NeoX locally
{
  # "data_path": "data/enwik8/enwik8_text_document",

  # or for weighted datasets:
  # "train-data-paths": ["data/enwik8/enwik8_text_document",],
  # "test-data-paths": ["data/enwik8/enwik8_text_document",],
  # "valid-data-paths": ["data/enwik8/enwik8_text_document",],

  "train-data-paths": ["/lustre/orion/bif151/proj-shared/data_shared/llama3_tokenized_datasets/dclm-baseline/train/dclm-baseline/merged_train",],
  "test-data-paths": ["/lustre/orion/bif151/proj-shared/data_shared/llama3_tokenized_datasets/dclm-baseline/train/dclm-baseline/merged_test",],
  "valid-data-paths":["/lustre/orion/bif151/proj-shared/data_shared/llama3_tokenized_datasets/dclm-baseline/train/dclm-baseline/merged_val",],

  "train-data-weights": [1.,],
  "test-data-weights": [1., ],
  "valid-data-weights": [1.,],

  # If weight_by_num_documents is True, Builds dataset weights from a multinomial distribution over groups of data according to the number of documents in each group.
  # WARNING: setting this to True will override any user provided weights
  # "weight_by_num_documents": false,
  # "weighted_sampler_alpha": 0.3,
  "vocab-file": "data/20B_tokenizer.json",
  # "vocab_file": "data/Meta-Llama-3-8B/tokenizer.json",
  "tokenizer_type": "HFTokenizer",
  # "tokenizer_type": "Llama3HFTokenizer",
  # "merge_file": "data/gpt2-merges.txt",

  # "train-dataset-name": 'dclm_train',
  # "val-dataset-name": 'dclm_val',

  "save": "checkpoints",
  "load": "checkpoints/abcd",
  "checkpoint_validation_with_forward_pass": False,

  "tensorboard_dir": "tensorboard",
  "log_dir": "logs",
  "finetune": true,
  "launcher": "slurm",
  "deepspeed_slurm": true  

  # "use_wandb": True,
  # "wandb_host": "https://api.wandb.ai",
  # "wandb_project": "neox"
}
