{ 
  "pipe_parallel_size": 1,
  "model_parallel_size": 1,
   # model settings
   "num_layers": 12,
   "hidden_size": 768,
   "num_attention_heads": 12,
   "seq_length": 2048,
   "max_position_embeddings": 2048,
   "norm": "layernorm",
   "pos_emb": "rotary",
   "no_weight_tying": true,
   "gpt_j_residual": false,
   "output_layer_parallelism": "column",

   # these should provide some speedup but takes a while to build, set to true if desired
   "scaled_upper_triang_masked_softmax_fusion": false,
   "bias_gelu_fusion": false,
   "rope_fusion": false,
   "layernorm_fusion": false,

   # init methods
   "init_method": "small_init",
   "output_layer_init_method": "wang_init",


   # these should provide some speedup but takes a while to build, set to true if desired
   "scaled_upper_triang_masked_softmax_fusion": false,
   "bias_gelu_fusion": false,
   "rope_fusion": false,
   "layernorm_fusion": false,

   # optimizer settings
   "optimizer": {
      "type": "Adam",
      "params": {
        "lr": 3.0e-4,
        "betas": [0.9, 0.95],
        "eps": 1.0e-8,
      }
    },
  "min_lr": 3.0e-5,
  "lr-decay-style": "cosine",
  # "num_repeats": 3,
  "warmup": 0.01,


   # for all zero_optimization options, see https://www.deepspeed.ai/docs/config-json/#zero-optimizations-for-fp16-training
   "zero_optimization": {
    "stage": 0,
    "allgather_partitions": True,
    "allgather_bucket_size": 500000000,
    "overlap_comm": True,
    "reduce_scatter": True,
    "reduce_bucket_size": 500000000,
    "contiguous_gradients": True,
  },

   # batch / data settings
   "train_micro_batch_size_per_gpu": 2,
   "data_impl": "mmap",
   "split": "949,50,1",

   # activation checkpointing
   "checkpoint_activations": true,
   "checkpoint_num_layers": 1,
   "partition_activations": true,
   "synchronize_each_layer": true,

   # regularization
   "gradient_clipping": 1.0,
   "weight_decay": 0.0,
   "hidden_dropout": 0.0,
   "attention_dropout": 0.0,

   # precision settings
   "fp16": {
     "enabled": true,
     "loss_scale": 0,
     "loss_scale_window": 1000,
     "hysteresis": 2,
     "min_loss_scale": 1
   },

   # misc. training settings
   "train_iters": 6500,
   "save_iters": [500, 1000, 1500, 2000, 2500, 3000, 3500, 4000, 4500, 5000, 5500, 6000, 6500],
   "lr_decay_iters": 210000,
   "distributed_backend": "nccl",
   "checkpoint_factor": 10000,
   "eval_interval": 10000,
   "eval_iters": 0,

   # logging
   "log_interval": 100,
   "steps_per_print": 10,
   "keep_last_n_checkpoints": 4,
   "wall_clock_breakdown": true,


  "train_data_paths": ["/lustre/orion/bif151/proj-shared/data/slim_pajama/tokenized_train_0-100B/ArXiv/ArXiv","/lustre/orion/bif151/proj-shared/data/slim_pajama/tokenized_train_0-100B/Book/Book","/lustre/orion/bif151/proj-shared/data/slim_pajama/tokenized_train_0-100B/C4/C4","/lustre/orion/bif151/proj-shared/data/slim_pajama/tokenized_train_0-100B/CommonCrawl/CommonCrawl","/lustre/orion/bif151/proj-shared/data/slim_pajama/tokenized_train_0-100B/Github/Github","/lustre/orion/bif151/proj-shared/data/slim_pajama/tokenized_train_0-100B/StackExchange/StackExchange","/lustre/orion/bif151/proj-shared/data/slim_pajama/tokenized_train_0-100B/Wikipedia/Wikipedia"],
  "test_data_paths": ["/lustre/orion/bif151/proj-shared/data/slim_pajama/test/all/sp_test"],
  "valid_data_paths": ["/lustre/orion/bif151/proj-shared/data/slim_pajama/test/all/sp_test"],
  # "valid_data_paths": ["/lustre/orion/bif151/proj-shared/data/slim_pajama/test/ArXiv/tokenized_arxiv_text_document", "/lustre/orion/bif151/proj-shared/data/slim_pajama/test/Book/tokenized_book_text_document","/lustre/orion/bif151/proj-shared/data/slim_pajama/test/C4/tokenized_c4_text_document","/lustre/orion/bif151/proj-shared/data/slim_pajama/test/CommonCrawl/tokenized_commoncrawl_text_document","/lustre/orion/bif151/proj-shared/data/slim_pajama/test/Github/tokenized_github_text_document","/lustre/orion/bif151/proj-shared/data/slim_pajama/test/StackExchange/tokenized_stackexchange_text_document","/lustre/orion/bif151/proj-shared/data/slim_pajama/test/Wikipedia/tokenized_wikipedia_text_document"],
  "split" : "50,30,20",
  # "label_data_paths": ["/lustre/orion/bif151/proj-shared/data/slim_pajama/tokenized_train_0-100B/ArXiv/ArXiv","/lustre/orion/bif151/proj-shared/data/slim_pajama/tokenized_train_0-100B/Book/Book"],
  "tensorboard_dir": "test_tensorboard",
  "tokenizer_type": "HFTokenizer",
  "vocab_file": "20B_checkpoints/20B_tokenizer.json",
  "checkpoint_validation_with_forward_pass": False,
  "use_wandb": False,
  "num_workers": 1,
  "finetune": true,
  "save": "checkpoints/pythia_125M_4500",
  "log_dir": "logs",
  "load": "checkpoints/pythia_125M_4500",

}