{ 
  "pipe_parallel_size": 1,
  "model_parallel_size": 1,

  # model settings
  "num_layers": 10,
  "hidden_size": 640,
  "num_attention_heads": 10,
  "seq_length": 2048,
  "max_position_embeddings": 2048,
  "pos_emb": "rotary",
  "rotary_pct": 0.25,
  "no_weight_tying": true,
  "gpt_j_residual": true,
  "output_layer_parallelism": "column",


  "attention-config": [[["global"], 10]],
  "init_method": "small_init",
  "output_layer_init_method": "wang_init",

  "activation": "silu",


   # these should provide some speedup but takes a while to build, set to true if desired
   "scaled_upper_triang_masked_softmax_fusion": false,
   "bias_gelu_fusion": false,
   "rope_fusion": false,
   "layernorm_fusion": false,

   # optimizer settings
   "optimizer": {
      "type": "Adam",
      "params": {
        "lr": 3.0e-4,
        "betas": [0.9, 0.95],
        "eps": 1.0e-8,
      }
    },
   "min_lr": 3.0e-5,
   "warmup": 0.01,

   # for all zero_optimization options, see https://www.deepspeed.ai/docs/config-json/#zero-optimizations-for-fp16-training
   "zero_optimization": {
    "stage": 0,
    "allgather_partitions": True,
    "allgather_bucket_size": 500000000,
    "overlap_comm": True,
    "reduce_scatter": True,
    "reduce_bucket_size": 500000000,
    "contiguous_gradients": True,
  },

   # batch / data settings
   "train_micro_batch_size_per_gpu": 2,
   "data_impl": "mmap",
   "split": "949,50,1",

   # activation checkpointing
   "checkpoint_activations": true,
   "checkpoint_num_layers": 1,
   "partition_activations": true,
   "synchronize_each_layer": true,

   # regularization
   "gradient_clipping": 1.0,
   "weight_decay": 0.0,
   "hidden_dropout": 0.0,
   "attention_dropout": 0.0,

   # precision settings
   "fp16": {
     "enabled": true,
     "loss_scale": 0,
     "loss_scale_window": 1000,
     "hysteresis": 2,
     "min_loss_scale": 1
   },

   # misc. training settings
   "train_iters": 3000,
   "lr_decay_iters": 21000,
   "distributed_backend": "nccl",
   "lr_decay_style": "cosine",
   "warmup": 0.01,
   "checkpoint_factor": 10000,
   "eval_interval": 10000,
   "eval_iters": 0,

   # logging
   "log_interval": 100,
   "steps_per_print": 10,
   "keep_last_n_checkpoints": 4,
   "wall_clock_breakdown": true,


  "train_data_paths": ["data/slim_pajama/tokenized_train_0-100B/ArXiv/ArXiv","data/slim_pajama/tokenized_train_0-100B/Book/Book","data/slim_pajama/tokenized_train_0-100B/C4/C4","data/slim_pajama/tokenized_train_0-100B/CommonCrawl/CommonCrawl","data/slim_pajama/tokenized_train_0-100B/Github/Github","data/slim_pajama/tokenized_train_0-100B/StackExchange/StackExchange","data/slim_pajama/tokenized_train_0-100B/Wikipedia/Wikipedia"],
  "test_data_paths": ["data/slim_pajama/test/all/sp_test"],
  "valid_data_paths": ["data/slim_pajama/test/all/sp_test"],
  # "valid_data_paths": ["data/slim_pajama/test/ArXiv/tokenized_arxiv_text_document", "data/slim_pajama/test/Book/tokenized_book_text_document","data/slim_pajama/test/C4/tokenized_c4_text_document","data/slim_pajama/test/CommonCrawl/tokenized_commoncrawl_text_document","data/slim_pajama/test/Github/tokenized_github_text_document","data/slim_pajama/test/StackExchange/tokenized_stackexchange_text_document","data/slim_pajama/test/Wikipedia/tokenized_wikipedia_text_document"],
  "split" : "20,75,5",
  # "label_data_paths": ["data/slim_pajama/tokenized_train_0-100B/ArXiv/ArXiv","data/slim_pajama/tokenized_train_0-100B/Book/Book"],
  "tensorboard_dir": "test_tensorboard",
  "tokenizer_type": "HFTokenizer",
  "vocab_file": "20B_checkpoints/20B_tokenizer.json",
  "checkpoint_validation_with_forward_pass": False,
  "use_wandb": False,
  "num_workers": 1,
  "finetune": true,
  "save": "checkpoints/ssm_pretrain/final",
  "log_dir": "logs",

}