{
  "pipe_parallel_size": 1,
  "model_parallel_size": 1,
  "num_layers": 24,
  "hidden_size": 1024,
  "num_attention_heads": 16,
  "seq_length": 2048,
  "max_position_embeddings": 2048,
  "pos_emb": "rotary",
  "rotary_pct": 0.25,
  "no_weight_tying": true,
  "gpt_j_residual": true,
  "output_layer_parallelism": "column",
  #  "attention_config": [[["flash"], 24]],
   "scaled_upper_triang_masked_softmax_fusion": true,
   "bias_gelu_fusion": false,
   "rope_fusion": false,
   "layernorm_fusion": true,
  "optimizer": {
    "type": "Adam",
    "params": {
      "lr": 5.0e-4,
      "betas": [0.9, 0.95],
      "eps": 1.0e-8,
    }
  },
  "min_lr": 5.0e-5,
  "lr_decay_style": "cosine",
  "warmup": 0.01,
   "zero_optimization": {
    "stage": 1,
    "allgather_partitions": true,
    "allgather_bucket_size": 200000000,
    "overlap_comm": true,
    "reduce_scatter": true,
    "reduce_bucket_size": 200000000,
    "contiguous_gradients": true,
    "cpu_offload": false
  },
   "train_micro_batch_size_per_gpu": 4,
   "gradient_accumulation_steps": 1,
   "data_impl": "mmap",
   "checkpoint_activations": true,
   "checkpoint_num_layers": 1,
   "partition_activations": true,
   "synchronize_each_layer": true,
   "gradient_clipping": 1.0,
   "weight_decay": 0.1,
   "hidden_dropout": 0.0,
   "attention_dropout": 0.0,
  "precision": "bfloat16",
  "fp32_allreduce": true,
  "bf16": {
    "enabled": true
  },
  "data_types": {
    "grad_accum_dtype": "fp32"
  },
   "train_iters": 143052,
   "lr_decay_iters": 143052,
   "distributed_backend": "nccl",
   "checkpoint_factor": 1000,
   "eval_interval": 100,
   "eval_iters": 100,
   "log_interval": 10,
   "steps_per_print": 10,
   "keep_last_n_checkpoints": 4,
   "wall_clock_breakdown": true,
   "launcher": "slurm",
   "deepspeed_slurm": true,
   "num_workers": 8,


  #  ########OSCAR Deutsch ######################
    "train_data_paths": [
    "/lustre/orion/bif151/proj-shared/data_shared/llama3_tokenized_datasets/dclm-baseline/train_400B/dclm-baseline/merged_train",
    "/lustre/orion/bif151/proj-shared/data_shared/llama3_tokenized_datasets/oscar-de/train/de/merged_train",
    "/lustre/orion/bif151/proj-shared/data_shared/llama3_tokenized_datasets/oscar-fr/train/fr/merged_train",


    ],
    
   "test_data_paths": ["/lustre/orion/bif151/proj-shared/data_shared/llama3_tokenized_datasets/dclm-baseline/test/dclm-baseline/merged_test",
    "/lustre/orion/bif151/proj-shared/data_shared/llama3_tokenized_datasets/oscar-de/test/de/merged_test",
   "/lustre/orion/bif151/proj-shared/data_shared/llama3_tokenized_datasets/oscar-fr/test/fr/merged_test",
   ],
   "valid_data_paths": [
    "/lustre/orion/bif151/proj-shared/data_shared/llama3_tokenized_datasets/dclm-baseline/val/dclm-baseline/merged_val",
    "/lustre/orion/bif151/proj-shared/data_shared/llama3_tokenized_datasets/oscar-de/val/de/merged_val",
    "/lustre/orion/bif151/proj-shared/data_shared/llama3_tokenized_datasets/oscar-fr/val/fr/merged_val",
   ],



  # #  ########OSCAR FR ######################
  #   "train_data_paths": [
  #   "/lustre/orion/bif151/proj-shared/data_shared/llama3_tokenized_datasets/oscar-fr/train/fr/merged_train",

  #   ],
  #   "forget_path":"forgetting_test/forgetting.pth",
    
  #  "test_data_paths": ["/lustre/orion/bif151/proj-shared/data_shared/llama3_tokenized_datasets/oscar-fr/test/fr/merged_test",],
  #  "valid_data_paths": ["/lustre/orion/bif151/proj-shared/data_shared/llama3_tokenized_datasets/oscar-fr/val/fr/merged_val",],

  #  ########DCLM######################
  #   "train_data_paths": [
  #   "/lustre/orion/bif151/proj-shared/data_shared/llama3_tokenized_datasets/dclm-baseline/train_400B/dclm-baseline/merged_train",

  #   ],
  #   "forget_path":"forgetting_test/forgetting.pth",
    
  #  "test_data_paths": ["/lustre/orion/bif151/proj-shared/data_shared/llama3_tokenized_datasets/dclm-baseline/test/dclm-baseline/merged_test",],
  #  "valid_data_paths": ["/lustre/orion/bif151/proj-shared/data_shared/llama3_tokenized_datasets/dclm-baseline/val/dclm-baseline/merged_val",],
  # "train_data_weights": [
  #   2.3135984956768517, #CC
  #   ],


  "train_proportion": [
    47684,47684,47684, # hatit bel id fl blundable ya ista
  ],

  "extra_save_iters": [2500, 4500, 6750, 11250, 13500],

    
  "forget_path":"llama3_multilang_haggani/forgetting.pth",

  "weight_by_num_documents": true,
   "split" : "80,10,10",
  #  "tokenizer_type": "HFTokenizer",
  #  "vocab_file": "/lustre/orion/bif151/proj-shared/Meta-Llama-3-8B/tokenizer.json",
   "vocab-file": "/lustre/orion/bif151/proj-shared/Meta-Llama-3-8B/tokenizer.json",
  #  "use_replay": true,
  #  "buffer_size": 3200000000,
  #  "file_size": 3200000,
  #  "replay_buffer_proportion" : 0.5,
  #  "fill_buffer_size": 2000,
   "split" : "80,10,10",
   "tokenizer_type": "Llama3HFTokenizer",
  #  "vocab_file": "/lustre/orion/bif151/proj-shared/Meta-Llama-3-8B/tokenizer.json",

  #  "buffer_dir": "data/buffer_save/pythia_410M_with_buffer/",
  "deepspeed_mpi": true,
  "save": "checkpoints/llama3_410M_multilangual_haggani",
  "log_dir": "logs",
  "load": "checkpoints/llama3_410M_multilangual_haggani",
  # "tensorboard_dir": "tensorboard_important/pythia_410M_kemel",
  "wandb_project":"llama3_410M_multilangual_haggani",
  "wandb_team":"istabrak",
  # "use_wandb": false,
}


