{
  "pipe_parallel_size": 1,
  "model_parallel_size": 1,
  "num_layers": 26,
  "hidden_size": 2048,
  "intermediate_size": 24576,
  "num_attention_heads": 16,
  "seq_length": 2048,
  "max_position_embeddings": 2048,
  "pos_emb": "rotary",
  "rotary_pct": 1,
  "no_weight_tying": true,
  "gpt_j_residual": false,
  "output_layer_parallelism": "column",
  "rms_norm_epsilon": 1.0e-5,
  "activation": "swiglu",
  # "use_flashattn_swiglu": true,

  "attention_config": [[["flash"], 26]],

  "scaled_upper_triang_masked_softmax_fusion": true,
  "bias_gelu_fusion": false,
  "rope_fusion": false,

  "init_method": "small_init",
  "output_layer_init_method": "wang_init",

  "optimizer": {
    "type": "Adam",
    "params": {
      "lr": 0.0003,
      "betas": [0.9, 0.95],
      "eps": 1.0e-8
    }
  },
  "min_lr": 0.00003,

  "zero_optimization": {
    "stage": 1,
    "allgather_partitions": true,
    "allgather_bucket_size": 500000000,
    "overlap_comm": true,
    "reduce_scatter": true,
    "reduce_bucket_size": 500000000,
    "contiguous_gradients": true,
    "cpu_offload": false
  },

   "train_micro_batch_size_per_gpu": 48,
   "data_impl": "mmap",
   "split": "949,50,1",
   "num_workers": 2,

   "checkpoint_activations": true,
   "checkpoint_num_layers": 1,
   "partition_activations": true,
   "synchronize_each_layer": true,
   "gradient_clipping": 1.0,
   "weight_decay": 0.0,
   "hidden_dropout": 0.0,
   "attention_dropout": 0.0,
   "fp16": {
     "enabled": true,
     "loss_scale": 0,
     "loss_scale_window": 1000,
     "hysteresis": 2,
     "min_loss_scale": 1
   },
   "train_iters": 320000,
   "lr_decay_iters": 320000,
   "distributed_backend": "nccl",
   "lr_decay_style": "cosine",
   "warmup": 0.01,
   "checkpoint_factor": 10000,
   "eval_interval": 1000,
   "eval_iters": 10,
   "log_interval": 10,
   "steps_per_print": 10,
   "keep_last_n_checkpoints": 4,
   "wall_clock_breakdown": true,
   "launcher": "slurm",
   "deepspeed_slurm": true,
   "mlp_multiple_of": 256,
   "use_bias_in_mlp": false,
  # "train-data-paths": [
  #   "/lustre/orion/csc569/scratch/ashwinee/datasets/HuggingFaceFW___fineweb/sample-10BT/megatron-formatted/fineweb-train-00000-of-00102_text_document",
  #   # "/lustre/orion/csc569/scratch/ashwinee/datasets/HuggingFaceFW___fineweb/sample-10BT/megatron-formatted/fineweb-train-00001-of-00102_text_document",
  #   # "/lustre/orion/csc569/scratch/ashwinee/datasets/HuggingFaceFW___fineweb/sample-10BT/megatron-formatted/fineweb-train-00002-of-00102_text_document",
  #   # "/lustre/orion/csc569/scratch/ashwinee/datasets/HuggingFaceFW___fineweb/sample-10BT/megatron-formatted/fineweb-train-00003-of-00102_text_document",
  #   # "/lustre/orion/csc569/scratch/ashwinee/datasets/HuggingFaceFW___fineweb/sample-10BT/megatron-formatted/fineweb-train-00004-of-00102_text_document",
  #   # "/lustre/orion/csc569/scratch/ashwinee/datasets/HuggingFaceFW___fineweb/sample-10BT/megatron-formatted/fineweb-train-00005-of-00102_text_document",
  #   # "/lustre/orion/csc569/scratch/ashwinee/datasets/HuggingFaceFW___fineweb/sample-10BT/megatron-formatted/fineweb-train-00006-of-00102_text_document",
  #   # "/lustre/orion/csc569/scratch/ashwinee/datasets/HuggingFaceFW___fineweb/sample-10BT/megatron-formatted/fineweb-train-00007-of-00102_text_document",
  #   # "/lustre/orion/csc569/scratch/ashwinee/datasets/HuggingFaceFW___fineweb/sample-10BT/megatron-formatted/fineweb-train-00008-of-00102_text_document",
  #   # "/lustre/orion/csc569/scratch/ashwinee/datasets/HuggingFaceFW___fineweb/sample-10BT/megatron-formatted/fineweb-train-00009-of-00102_text_document",
  #   # "/lustre/orion/csc569/scratch/ashwinee/datasets/HuggingFaceFW___fineweb/sample-10BT/megatron-formatted/fineweb-train-00010-of-00102_text_document"
  # ],
  # "valid-data-paths": [
  #   "/lustre/orion/csc569/scratch/ashwinee/datasets/HuggingFaceFW___fineweb/sample-10BT/megatron-formatted/fineweb-train-00030-of-00102_text_document",
  # ],
  # "test-data-paths": [
  #   "/lustre/orion/csc569/scratch/ashwinee/datasets/HuggingFaceFW___fineweb/sample-10BT/megatron-formatted/fineweb-train-00031-of-00102_text_document",
  # ],
  # "vocab_file": "/lustre/orion/csc569/scratch/ashwinee/datasets/tokenizer.json",
  # "tokenizer_type": "HFTokenizer",
  # "tensorboard_dir": "tensorboard",
  # "log_dir": "logs",
  # "use_wandb": True,
  # "wandb_host": "https://api.wandb.ai",
  # "wandb_project": "neox"
}